AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    manyToMany:
        categories:
          targetEntity: Category
          mappedBy: products