AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
    manyToMany:
        categories:
          targetEntity: Category
          joinTable:
            name: products_categories
            joinColumns:
              product_id:
                referencedColumnName: id
            inverseJoinColumns:
              category_id:
                referencedColumnName: id